# Generated by Django 5.0.7 on 2024-08-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_payments_options_payments_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, max_length=50, verbose_name='дата последнего захода'),
        ),
    ]
