# Generated by Django 5.0.7 on 2024-07-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название курса')),
                ('photo', models.ImageField(help_text='Загрузите новое фото', upload_to='materials/photo', verbose_name='Фото')),
                ('description', models.TextField(max_length=200, verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название курса')),
                ('description', models.TextField(max_length=200, verbose_name='описание')),
                ('photo', models.ImageField(help_text='Загрузите новое фото', upload_to='materials/photo', verbose_name='Фото')),
            ],
        ),
    ]
